import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { cn } from '@/lib/utils';
import { NetworkBadge } from './NetworkBadge';
import { WalletButton } from './WalletButton';
import { ThemeToggle } from './ThemeToggle';
import { NotificationPanel } from './NotificationPanel';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { Zap, LayoutDashboard, Send, Activity, Search, Settings, Menu } from 'lucide-react';
import { Button } from '@/components/ui/button';